### ISSUE TITLE
Possible problem with NestJs 7.6.18 - Error: TypeError: req.get is not a function

### ISSUE THREAD

**Issue by dmdeklerk** [pragmaticivan/nestjs-otel#100]
With NestJs 7.6.18 (uses fastify 3.14.0) and nestjs-otel 2.4.0 we get the following error in our otherwise working app.
We are in the process of upgrading to NestJS 8 and will report if the problem persists.

**To reproduce**

Navigate to any route in the application

**Side note 1**

http://localhost:8081/metrics **does** work

**Side note 2**

The advertized Discord inivite link seems to be expired.

**Console error message**

```
[Nest] 85656   - 01/09/2021, 13:42:33   [ExceptionHandler] Error: TypeError: req.get is not a function
    at /Users/dirk/git/heat-server-aws/node_modules/nestjs-otel/lib/middleware/api-metrics.middleware.js:89:48
    at ServerResponse.onHeaders (/Users/dirk/git/heat-server-aws/node_modules/response-time/index.js:58:7)
    at ServerResponse.writeHead (/Users/dirk/git/heat-server-aws/node_modules/on-headers/index.js:35:16)
    at onSendEnd (/Users/dirk/git/heat-server-aws/node_modules/fastify/lib/reply.js:428:7)
    at onSendHook (/Users/dirk/git/heat-server-aws/node_modules/fastify/lib/reply.js:379:5)
    at preserializeHookEnd (/Users/dirk/git/heat-server-aws/node_modules/fastify/lib/reply.js:365:3)
    at preserializeHook (/Users/dirk/git/heat-server-aws/node_modules/fastify/lib/reply.js:345:5)
    at _Reply.Reply.send (/Users/dirk/git/heat-server-aws/node_modules/fastify/lib/reply.js:184:7)
    at FastifyAdapter.reply (/Users/dirk/git/heat-server-aws/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:46:29)
    at RouterResponseController.apply (/Users/dirk/git/heat-server-aws/node_modules/@nestjs/core/router/router-response-controller.js:13:36)
    at /Users/dirk/git/heat-server-aws/node_modules/@nestjs/core/router/router-execution-context.js:175:48
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /Users/dirk/git/heat-server-aws/node_modules/@nestjs/core/router/router-execution-context.js:47:13
    at async Object.<anonymous> (/Users/dirk/git/heat-server-aws/node_modules/@nestjs/core/router/router-proxy.js:9:17) +15ms
```

**Comment by dmdeklerk** [comment]
Same behavior on NestJs 8+

Seems Fastify does not allow `req.get()` to get the content length at location below.

```js
      const requestLength = parseInt(req.get('content-length'), 10) || 0;
      const responseLength: number = parseInt(res.get('Content-Length'), 10) || 0;
```

https://github.com/pragmaticivan/nestjs-otel/blob/main/src/middleware/api-metrics.middleware.ts#L124-L125

Perhaps `req.headers[]` provides these properties for Fastify? https://github.com/fastify/fastify/blob/main/lib/request.js#L163

**Comment by pragmaticivan** [comment]
@dmdeklerk thanks for reporting! Will take a look soon. PRs are also welcome 🎉

**Comment by dmdeklerk** [comment]
I can confirm that with NestJs 8+ with Fastify Adapter and **nestjs-otel 2.3.0** run fine. 

Thank you for this great tool @pragmaticivan it is of great help to get Prometheus metrics up and running fast for NestJs apps. We will be sure to report anything we run into.

**Comment by pragmaticivan** [comment]
@dmdeklerk discord link was updated. Try it now, thanks for the reminder!
