### ISSUE TITLE
Package broken with newest opentelemetry dependencies

### ISSUE THREAD

**Issue by MarcStdt** [pragmaticivan/nestjs-otel#151]
When using the latest opentelementy packages (0.27.0), the Nest application fails to start with the following error:

```
/home/node/app/node_modules/nestjs-otel/src/metrics/metric-data.ts:27
      const valueRecorder = meter.createValueRecorder(name, options);
                                  ^
TypeError: meter.createValueRecorder is not a function
    at getOrCreateValueRecorder (/home/node/app/node_modules/nestjs-otel/src/metrics/metric-data.ts:27:35)
    at MetricService.getOrCreateValueRecorder (/home/node/app/node_modules/nestjs-otel/src/metrics/metric.service.ts:26:36)
    at MetricService.getValueRecorder (/home/node/app/node_modules/nestjs-otel/src/metrics/metric.service.ts:20:17)
    at new ApiMetricsMiddleware (/home/node/app/node_modules/nestjs-otel/src/middleware/api-metrics.middleware.ts:90:47)
    at Injector.instantiateClass (/home/node/app/node_modules/@nestjs/core/injector/injector.js:301:19)
    at callback (/home/node/app/node_modules/@nestjs/core/injector/injector.js:48:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Injector.resolveConstructorParams (/home/node/app/node_modules/@nestjs/core/injector/injector.js:124:24)
    at async Injector.loadInstance (/home/node/app/node_modules/@nestjs/core/injector/injector.js:52:9)
    at async Injector.loadMiddleware (/home/node/app/node_modules/@nestjs/core/injector/injector.js:61:9)
```

**Comment by pragmaticivan** [comment]
That's actually great news 😂  I will try to patch that up this weekend, It will require a major version though. I've been keeping track of this release for a while but some packages might be moved somewhere else FYI.

Ref: https://github.com/open-telemetry/opentelemetry-js/issues/2480

**Comment by elbasan** [comment]
any news?

**Comment by pragmaticivan** [comment]
howdy @elbasan there's a WIP Pr coming up to fix that. Unfortunatelly since metrics API was experimental, there is not `major version bumps`.

**Comment by elbasan** [comment]
> howdy @elbasan there's a WIP Pr coming up to fix that. Unfortunately since metrics API was experimental, there is no `major version bumps`.

Hey there, thanks for the quick response. Could you maybe tell me about to which versions i should downgrade the otel libaries so it still works

**Comment by pragmaticivan** [comment]
@elbasan I need to check again but my current project is running `0.24.0`.

**Comment by marcbachmann** [comment]
I've fixed the compatibility with opentelemetry 0.27 in https://github.com/marcbachmann/opentelemetry-node-metrics/pull/3

**Comment by MattGson** [comment]
This still seems to be broken:

```
opentelemetry-node-metrics@1.1.0/node_modules/opentelemetry-node-metrics/metrics/version.js:17
  }).bind(version).add(1)
     ^
TypeError: meter.createUpDownCounter(...).bind is not a function
```

**Comment by marcbachmann** [comment]
The dependencies got updated on the branch `main`: https://github.com/pragmaticivan/nestjs-otel/commit/c2f8b7b9fbe116953521fb6b5d7f4648d09d7712#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R42

**Comment by pragmaticivan** [comment]
@MattGson could you share which packages you are using? (versions)

I have it working here https://github.com/pragmaticivan/nestjs-otel-prom-grafana-tempo (latest released version)

**Comment by simakwm** [comment]
> This still seems to be broken:
> 
> ```
> opentelemetry-node-metrics@1.1.0/node_modules/opentelemetry-node-metrics/metrics/version.js:17
>   }).bind(version).add(1)
>      ^
> TypeError: meter.createUpDownCounter(...).bind is not a function
> ```

@MattGson Maybe you forgot to do  `await otelSDK.start()` ?

**Comment by dkrylovdotcom** [comment]
The same problem:

```
TypeError: meter.createUpDownCounter(...).bind is not a function
    at module.exports (/Users/macos/Documents/work/projects/js/nodejs/nest-third-telemetry/node_modules/opentelemetry-node-metrics/metrics/version.js:17:6)
    at setupNodeMetrics (/Users/macos/Documents/work/projects/js/nodejs/nest-third-telemetry/node_modules/opentelemetry-node-metrics/index.js:18:31)
    at OpenTelemetryCoreModule.onApplicationBootstrap (/Users/macos/Documents/work/projects/js/nodejs/nest-third-telemetry/node_modules/nestjs-otel/src/opentelemetry-core.module.ts:110:44)
    at callModuleBootstrapHook (/Users/macos/Documents/work/projects/js/nodejs/nest-third-telemetry/node_modules/@nestjs/core/hooks/on-app-bootstrap.hook.js:51:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at NestApplication.callBootstrapHook (/Users/macos/Documents/work/projects/js/nodejs/nest-third-telemetry/node_modules/@nestjs/core/nest-application-context.js:198:13)
    at NestApplication.init (/Users/macos/Documents/work/projects/js/nodejs/nest-third-telemetry/node_modules/@nestjs/core/nest-application.js:98:9)
    at NestApplication.listen (/Users/macos/Documents/work/projects/js/nodejs/nest-third-telemetry/node_modules/@nestjs/core/nest-application.js:155:33)
    at bootstrap (/Users/macos/Documents/work/projects/js/nodejs/nest-third-telemetry/src/main.ts:26:3)
```

package.json:  
```
"dependencies": {
    "@nestjs/common": "^8.1.1",
    "@nestjs/core": "^8.1.1",
    "@nestjs/platform-express": "^8.1.1",
    "@opentelemetry/auto-instrumentations-node": "0.27.1",
    "@opentelemetry/sdk-node": "0.27.0",
    "nestjs-otel": "^3.0.4",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.4.0"
  },
```


`await otelSDK.start();` in place, but it seems like problem happens when NodeSDK constructs

**Comment by schoenbergerb** [comment]
same problem, but if I set `metrics.defautMetrics` to `false` in the module options the service comes up

**Comment by fuergaosi233** [comment]
> same problem, but if I set `metrics.defautMetrics` to `false` in the module options the service comes up

It works for me, and I have to turn off this switch to use it

**Comment by pragmaticivan** [comment]
Investigating the changes, be aware that metrics SDK in JS is not stable and this package support for metrics aim to give it as a tease before 1.0. It's unlikely you might get quick support by underlying packages, so I would slow down a bit on updating packages related to metrics.

**Comment by issackr** [comment]
hey @pragmaticivan I'm using the same packages versions from here:
https://github.com/pragmaticivan/nestjs-otel-prom-grafana-tempo

but still get such errors:
[gateway] Error in getConfigurations: this.metricService.getValueRecorder is not a function

where metricService is 
import { MetricService } from 'nestjs-otel';

**Comment by brpaz** [comment]
Hello. I am also getting this error:

```
opentelemetry-node-metrics@1.1.0/node_modules/opentelemetry-node-metrics/metrics/version.js:17
  }).bind(version).add(1)
     ^
TypeError: meter.createUpDownCounter(...).bind is not a function
```

From what I understood this was fixed [here](https://github.com/marcbachmann/opentelemetry-node-metrics/pull/7) in the `opentelemetry-node-metrics.`. which is already the version on the main branch on this repo, but not in the latest released tag.

@pragmaticivan Any chance to create a new release?

**Comment by 1eedaegon** [comment]
For those in a hurry, here is a solution:

const OpenTelemetryModuleConfig = OpenTelemetryModule.forRoot({
  metrics: {
    ...blah
    // defaultMetrics: true, <- ** commented this line **
    ...blah
    },
  },
});

**Comment by austonpramodh** [comment]
For me, the below worked. 

It seems to be an issue with the old version(1.1.0) of `opentelemetry-node-metrics` package being used. Forcing the dependency package manager to install the latest version of  `opentelemetry-node-metrics` did the trick for me.

add the following in `package.json`
![image](https://user-images.githubusercontent.com/5049050/185860000-f9d902b3-2dc2-45db-a481-861cb0f66af8.png)

btw, I am using `yarn`. This won't work for `npm`.

npm users: https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions
yarn users: https://stackoverflow.com/questions/40226639/how-do-i-override-nested-dependencies-with-yarn

**Comment by pragmaticivan** [comment]
Working example here: https://github.com/pragmaticivan/nestjs-otel-prom-grafana-tempo
