### ISSUE TITLE
Problem with more then one span

### ISSUE THREAD

**Issue by kosmos** [pragmaticivan/nestjs-otel#45]
I observe very strange behavior. If the application has more than one span, then information about them is not sent to the collector (I use Jaeger).

This works and I can see span in Jaeger:
```
  @Span('doSomething')
  async doSomething() {
    console.log('');
  }
```

But this code does not send any spans to Jaeger:
```
  @Span('doSomething')
  async doSomething() {
    console.log('doSomething');
  }

  @Span('doSomethingElse')
  async doSomethingElse() {
    console.log('doSomethingElse');
  }
```

I also get the same  behavior if I add any nested span using TraceService or if I add any instrumentation.

I use next config:
```
const OpenTelemetryModuleConfig = OpenTelemetryModule.forRoot({
  metrics: {
    hostMetrics: true,
    defaultMetrics: true, 
    apiMetrics: {
      enable: true, 
      timeBuckets: [],
    },
  },
  nodeSDKConfiguration: {
    spanProcessor: new BatchSpanProcessor(new JaegerExporter({
      host: 'host.docker.internal',
      port: 6832,
    })),
    contextManager: new AsyncLocalStorageContextManager(),
    textMapPropagator: new CompositePropagator({
      propagators: [
        new B3Propagator(),
        new B3Propagator({
          injectEncoding: B3InjectEncoding.MULTI_HEADER,
        }),
      ],
    }),
    resource: new Resource({
      [ResourceAttributes.SERVICE_NAME]: 'stl',
    }),
  },
});
```

**Comment by pragmaticivan** [comment]
Wiill take a look. Might be related to `https://github.com/pragmaticivan/nestjs-otel/issues/42`

**Comment by kosmos** [comment]
Looks like the problem in JaegerExporter. If I replace it with ConsoleExporter I can see more spans. Or that can be a probblem with UDP ports of Jaeger in Docker.

**Comment by pragmaticivan** [comment]
@kosmos 

Try setting that:

```
import { diag, DiagLogLevel } from '@opentelemetry/api';
diag.setLogger(console, DiagLogLevel.ALL);
```

before `OpenTelemetryModule.forRoot`.

It seems to be related to the jaeger package integration with docker:

```
{"stack":"Error: error sending spans over UDP: Error: send EMSGSIZE localhost:6832, packet size: 20125, bytes sent: undefined\n    at /Users/isantos/Code/pragmaticivan/rd-api/node_modules/@opentelemetry/exporter-jaeger/build/src/jaeger.js:151:35\n    at Function.invokeCallback (/Users/isantos/Code/pragmaticivan/rd-api/node_modules/jaeger-client/dist/src/reporters/sender_utils.js:33:9)\n    at /Users/isantos/Code/pragmaticivan/rd-api/node_modules/jaeger-client/dist/src/reporters/udp_sender.js:180:34\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","message":"error sending spans over UDP: Error: send EMSGSIZE localhost:6832, packet size: 20125, bytes sent: undefined","name":"Error"}
```

Is that what you are getting?

**Comment by pragmaticivan** [comment]
It seems to be related to Jaeger lib usage.

Try:
```
spanProcessor: new BatchSpanProcessor(new JaegerExporter({
      endpoint: 'http://0.0.0.0:14268/api/traces'
    })),
```

**Comment by pragmaticivan** [comment]
Closing that for now. Feel free to message here if that's not the case.

**Comment by pragmaticivan** [comment]
@chrismllr I've just added a full example: https://github.com/pragmaticivan/nestjs-otel/tree/main/examples/nestjs-prom-grafana-tempo

This one has grafana + prometheus + tempo + jaeger ui.
In the logs you can copy the `traceId` and can search it on Jaeger UI or Tempo directly on Grafana.
