### ISSUE TITLE
nestjs-otel tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

### ISSUE THREAD

**Issue by coler-j** [pragmaticivan/nestjs-otel#512]
Getting the following when using node v22 and yarn 4.5.3 with pnp and upgrading to most recent version of `nestjs-otel`

```
Error: nestjs-otel tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: tslib
Required by: nestjs-otel@virtual:<hash>#npm:6.1.1 (via /project-path/.yarn/__virtual__/nestjs-otel-virtual-<hash>/0/cache/nestjs-otel-npm-6.1.1-<hash>zip/node_modules/nestjs-otel/lib/)

Require stack:
- /project-path/.yarn/__virtual__/nestjs-otel-virtual-<hash>/0/cache/nestjs-otel-npm-6.1.1-<hash>.zip/node_modules/nestjs-otel/lib/index.js
- /project-path/dist/instrumentation/instrumentation.module.js
- /project-path/dist/app.module.js
- /project-path/dist/main.js
    at require$$0.Module._resolveFilename (/project-path/.pnp.cjs:<hash>:13)
    at Function.<anonymous> (node:internal/modules/cjs/loader:1075:27)
    at require$$0.Module._load (/project-path/.pnp.cjs:<hash>:31)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.<anonymous> (node:internal/modules/cjs/loader:1340:12)
    at Hook._require.Module.require (/project-path/.yarn/cache/require-in-the-middle-npm-7.2.0-<hash>.zip/node_modules/require-in-the-middle/index.js:167:34)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/project-path/.yarn/__virtual__/nestjs-otel-virtual-<hash>/0/cache/nestjs-otel-npm-6.1.1-<hash>.zip/node_modules/nestjs-otel/lib/index.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)

Node.js v22.11.0

```

**Comment by coler-j** [comment]
I don't see `tslib` in the project dependencies, but I do see this reference:

https://github.com/pragmaticivan/nestjs-otel/blob/9466279deb1ed1344acf999929e429a71c9d3ba3/tsconfig.json#L21

**Comment by coler-j** [comment]
> "tslib is not a dependency of angular itself. But rather a dependency of the TypeScript compiler when you enable TypeScript importHelpers. Any library that is compiled using importHelpers should always have a direct dependency on tslib and not rely on other libraries to install it."

It looks like you should be adding tslib as a direct dependency of your project.

**Comment by Papooch** [comment]
IMHO this should be removed (set to `false` for the library). If there's a significant mismatch between the version of typescript used to build this library and the version of typescript used to build the application, it could cause issues.
